server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
  playground:
    cdn:
      version: latest
altair:
  enabled: true
  cdn:
    enabled: false
graphiql:
  enabled: true
  cdn:
    enabled: true
    version: 0.17.5
voyager:
  enabled: true
  cdn:
    enabled: false
graphql.playground:
  enabled: true
  cdn:
    enabled: false


spring:
  influxdb:
    url: http://influxdb:8086
    username: influx
    password: influx
    database: meteo
    retention-policy: autogen
    connect-timeout: 40
    read-timeout: 60
    write-timeout: 60
#    enable-gzip: false
