server:
  port: 8080

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

#graphiql:
#  mapping: /graphiql
#  endpoint: /graphql
#  enabled: true
#  pageTitle: GraphiQL
#  cdn:
#    enabled: false
#    version: 0.11.11


spring:
  influxdb:
    url: http://influxdb:8086
    username: influx
    password: influx
    database: meteo
    retention-policy: autogen
    connect-timeout: 40
    read-timeout: 60
    write-timeout: 60
#    enable-gzip: false
